#!name=VSCO

#!desc=NVNPTIT

#!icon=https://raw.githubusercontent.com/deezertidal/private/main/icons/vsco.png

[Script]

VSCO=type=http-request,pattern=^https?:\/\/api\.revenuecat\.com\/v\d\/subscribers\/,script-path=https://raw.githubusercontent.com/nvnptit/wsrz/main/vsco.js

VSCO1=type=http-response,pattern=^https?:\/\/api\.revenuecat\.com\/v\d\/subscribers\/,requires-body=1,script-path=https://raw.githubusercontent.com/nvnptit/wsrz/main/vsco.js



[MITM]

hostname= %APPEND% api.revenuecat.com

