#!name=VSCO

#!desc=Unlock VSCO

#!icon=https://raw.githubusercontent.com/deezertidal/private/main/icons/vsco.png

#!homepage=https://whatshub.top

#!author=NobyDa

[Script]

VSCO=type=http-request,pattern=^https?:\/\/api\.revenuecat\.com\/v\d\/subscribers\/,script-path=https://raw.githubusercontent.com/NobyDa/Script/master/QuantumultX/File/vsco.js

VSCO1=type=http-response,pattern=^https?:\/\/api\.revenuecat\.com\/v\d\/subscribers\/,requires-body=1,script-path=https://raw.githubusercontent.com/NobyDa/Script/master/QuantumultX/File/vsco.js



[MITM]

hostname= %APPEND% api.revenuecat.com

